project_id = "interview-ready"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000", "interviewready://auth/callback"]
jwt_expiry = 3600
enable_signup = true
email.enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_SECRET)"
redirect_uri = "interviewready://auth/callback"

[auth.external.linkedin_oidc]
enabled = true
client_id = "env(LINKEDIN_CLIENT_ID)"
secret = "env(LINKEDIN_SECRET)"
redirect_uri = "interviewready://auth/callback"

